# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-07 05:29
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Management', '0002_auto_20170407_0518'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
