# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-07 13:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin_Management', '0003_auto_20170407_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_email', models.CharField(max_length=120)),
                ('candidate_resume', models.CharField(max_length=100)),
                ('candidate_contact_no', models.CharField(max_length=15)),
                ('candiate_interview_time', models.DateTimeField(default=datetime.datetime(2017, 4, 7, 13, 13, 49, 294647))),
                ('caandidate_status', models.CharField(max_length=10, null=True)),
                ('consultancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Management.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=500)),
                ('question_status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(max_length=300)),
                ('requirement_status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_skill', models.CharField(max_length=50, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content_Management.Candidate')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content_Management.Requirements'),
        ),
    ]
