# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-07 13:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candiate_interview_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 7, 13, 14, 25, 706152)),
        ),
    ]
