# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Content_Management', '0005_auto_20170407_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='candiate_interview_time',
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_age',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_experience',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_interview',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_interview_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_ctc',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_ctc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notice_period',
            field=models.CharField(default='IMMEDIATE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questions',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='requirements',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='skillset',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_resume',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_status',
            field=models.CharField(default='VALID', max_length=10, null=True),
        ),
    ]
