# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content_Management', '0006_auto_20170410_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_experience',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_ctc',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expected_ctc',
            field=models.FloatField(default=0.0),
        ),
    ]
