# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-02 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Management', '0003_auto_20170407_0529'),
        ('Content_Management', '0007_auto_20170422_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consultancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Management.CustomUser')),
            ],
        ),
    ]
