# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-02 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content_Management', '0008_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='candidate_id',
            field=models.IntegerField(default=0),
        ),
    ]
