# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-10 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content_Management', '0009_activities_candidate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='requirement_description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
