# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-10 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Content_Management', '0011_auto_20170510_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='requirements',
            new_name='requirement',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='candidate_id',
        ),
        migrations.AddField(
            model_name='activities',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Content_Management.Candidate'),
        ),
        migrations.AddField(
            model_name='activities',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Content_Management.Questions'),
        ),
        migrations.AddField(
            model_name='activities',
            name='requirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Content_Management.Requirements'),
        ),
        migrations.AddField(
            model_name='skillset',
            name='requirement_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activities',
            name='consultancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_Management.CustomUser'),
        ),
    ]
