# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-10 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Content_Management', '0012_auto_20170510_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='candidate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Content_Management.Candidate'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='consultancy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_Management.CustomUser'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Content_Management.Questions'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='requirement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Content_Management.Requirements'),
        ),
    ]
