# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-10 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Content_Management', '0013_auto_20170510_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillset',
            name='requirement_id',
        ),
        migrations.AddField(
            model_name='skillset',
            name='requirement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Content_Management.Requirements'),
        ),
    ]
