# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Content_Management', '0016_candidate_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='position_state',
            field=models.CharField(default='Open', max_length=10),
        ),
        migrations.AddField(
            model_name='skillset',
            name='skill_description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='candidate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Content_Management.Candidate'),
        ),
    ]
