# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Content_Management', '0017_auto_20170514_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='Other Skill', max_length=50)),
                ('description', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content_Management.Positions')),
            ],
        ),
        migrations.RemoveField(
            model_name='skillset',
            name='candidate_skill',
        ),
        migrations.RemoveField(
            model_name='skillset',
            name='position',
        ),
        migrations.RemoveField(
            model_name='skillset',
            name='skill_description',
        ),
        migrations.AddField(
            model_name='skillset',
            name='master_field',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Content_Management.MasterSkills'),
            preserve_default=False,
        ),
    ]
