# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Content_Management', '0018_auto_20170515_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='candidate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Content_Management.Candidate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skillset',
            name='master_field',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Content_Management.MasterSkills'),
        ),
    ]
