# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content_Management', '0022_auto_20170517_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_status',
            field=models.CharField(default='New', max_length=50, null=True),
        ),
    ]
